### ISSUE TITLE
Doesn't work without any chooser installed

### ISSUE THREAD

**Issue by trygveaa** [emersion/xdg-desktop-portal-wlr#138] opened 2021-05-21 12:01 UTC
The man page says that the chooser will fallback to an arbitrary output if no chooser is found. However, that doesn't happen for me. If I try to share the screen without any chooser installed, it doesn't work. I tested with Google Meet in Firefox and after I click allow in Firefox, nothing happens.

If I install slurp, it works as expected.

<details>
<summary>In case it's useful, here is the debug log when no chooser is installed:</summary>

```
2021/05/21 13:53:15 [INFO] - dbus: create session method invoked
2021/05/21 13:53:15 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_46/webrtc729454168
2021/05/21 13:53:15 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_46/webrtc_session1984468611
2021/05/21 13:53:15 [INFO] - dbus: app_id: 
2021/05/21 13:53:15 [INFO] - dbus: select sources method invoked
2021/05/21 13:53:15 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_46/webrtc241991217
2021/05/21 13:53:15 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_46/webrtc_session1984468611
2021/05/21 13:53:15 [INFO] - dbus: app_id: 
2021/05/21 13:53:15 [INFO] - dbus: option types:3
2021/05/21 13:53:15 [INFO] - dbus: option multiple: 0
2021/05/21 13:53:15 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_46/webrtc_session1984468611
2021/05/21 13:53:15 [INFO] - wlroots: capturable output: Unknown model: 0xD291: id: 39 name: eDP-1
2021/05/21 13:53:15 [DEBUG] - wlroots: output chooser called
2021/05/21 13:53:15 [DEBUG] - wlroots: output chooser called
/bin/sh: line 1: slurp: command not found
2021/05/21 13:53:15 [DEBUG] - wlroots: output chooser canceled
2021/05/21 13:53:15 [ERROR] - wlroots: no output found
2021/05/21 13:53:15 [INFO] - dbus: session closed
2021/05/21 13:53:15 [DEBUG] - dbus: destroying session 0x5575580b0270
```
</details>

<details>
<summary>And this is the debug log after slurp is installed and it works:</summary>

```
2021/05/21 13:58:47 [INFO] - dbus: create session method invoked
2021/05/21 13:58:47 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_46/webrtc1472122547
2021/05/21 13:58:47 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_46/webrtc_session1833687642
2021/05/21 13:58:47 [INFO] - dbus: app_id: 
2021/05/21 13:58:47 [INFO] - dbus: select sources method invoked
2021/05/21 13:58:47 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_46/webrtc973539335
2021/05/21 13:58:47 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_46/webrtc_session1833687642
2021/05/21 13:58:47 [INFO] - dbus: app_id: 
2021/05/21 13:58:47 [INFO] - dbus: option types:3
2021/05/21 13:58:47 [INFO] - dbus: option multiple: 0
2021/05/21 13:58:47 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_46/webrtc_session1833687642
2021/05/21 13:58:47 [INFO] - wlroots: capturable output: Unknown model: 0xD291: id: 39 name: eDP-1
2021/05/21 13:58:47 [DEBUG] - wlroots: output chooser called
2021/05/21 13:58:47 [DEBUG] - wlroots: output chooser called
2021/05/21 13:58:55 [DEBUG] - wlroots: output chooser selects eDP-1
2021/05/21 13:58:55 [INFO] - xdpw: screencast instance 0x5575580bc0a0 has 1 references
2021/05/21 13:58:55 [INFO] - xdpw: 1 active screencast instances
2021/05/21 13:58:55 [INFO] - wlroots: output: eDP-1
2021/05/21 13:58:55 [INFO] - dbus: start method invoked
2021/05/21 13:58:55 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_46/webrtc931700331
2021/05/21 13:58:55 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_46/webrtc_session1833687642
2021/05/21 13:58:55 [INFO] - dbus: app_id: 
2021/05/21 13:58:55 [INFO] - dbus: parent_window: 
2021/05/21 13:58:55 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_46/webrtc_session1833687642
2021/05/21 13:58:55 [DEBUG] - wlroots: reset buffer
2021/05/21 13:58:55 [DEBUG] - wlroots: create shm buffer
2021/05/21 13:58:55 [DEBUG] - pipewire: registered event 0x5575580b5e50
2021/05/21 13:58:55 [INFO] - pipewire: stream state changed to "connecting"
2021/05/21 13:58:55 [INFO] - pipewire: node id is -1
2021/05/21 13:58:55 [INFO] - pipewire: stream state changed to "paused"
2021/05/21 13:58:55 [INFO] - pipewire: node id is 86
2021/05/21 13:58:55 [INFO] - pipewire: stream state changed to "streaming"
2021/05/21 13:58:55 [INFO] - pipewire: node id is 86
```
</details>

As a sidenote, if you only have one output, there's no point in triggering the chooser, is there? It could just select that one output immediately?

**Comment by danshick** [comment] 2021-05-21 12:16
Hmmm, sounds like a bug. Do you have any config file at all? Either that or we introduced a bug when we switched to inih (probably both actually).

The only benefit of allowing choosers in single screen setups is to allow the user to cancel a screenshare request (usually by pressing eacape in slurp/dmenu).

You can write a config file per the man page that will use a fixed output.

**Comment by trygveaa** [comment] 2021-05-21 13:26
No, I don't have any config file. I'm just using it as it comes in the Arch Linux package, and as far as I can see, that doesn't include any config.

> The only benefit of allowing choosers in single screen setups is to allow the user to cancel a screenshare request (usually by pressing eacape in slurp/dmenu).

Yeah, okay.

> You can write a config file per the man page that will use a fixed output.

Well, I would still like to be able to select an output when I have multiple outputs.

**Comment by danshick** [comment] 2021-05-21 13:50
Gotcha. Whelp, this sounds like our bug then. Let me see if I can reproduce it.

**Comment by danshick** [comment] 2021-05-21 14:06
Yup, can confirm...
[xdpw.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/6523071/xdpw.log)

**Comment by danshick** [comment] 2021-05-21 14:11
Good news, this is already fixed in recent changes since the last release...
[xdpw.log](https://github.com/emersion/xdg-desktop-portal-wlr/files/6523092/xdpw.log)

You can either wait for a new release, install [xdg-desktop-portal-wlr-git from the AUR
](https://aur.archlinux.org/packages/xdg-desktop-portal-wlr-git/), or build (and optionally install) it manually. I would recommend option 2 personally.

We should do a new release soon to get this fix packaged.

**Comment by danshick** [comment] 2021-05-21 14:12
Closing this issue as resolved.

**Closed by danshick** 2021-05-21 14:12 UTC
Labels: bug

**Comment by trygveaa** [comment] 2021-05-23 09:00
Thanks! I can confirm it works fine in master.
