### ISSUE TITLE
screencast: let the user select the output

### ISSUE THREAD

**Issue by emersion** [emersion/xdg-desktop-portal-wlr#12] opened 2020-03-13 20:08 UTC
Right now we have a CLI option, which is less than ideal. Replace this with a basic UI, probably slurp-based.

xdg-output can be used to obtain output geometry in logical coordinates. A list of rectangles can be fed to slurp on stdin.

**Comment by tmccombs** [comment] 2020-05-12 05:45
> Replace this with a basic UI, probably slurp-based.

It would be nice to have something like this for screenshots as well. I also think it would be good to have a way to select whether to use a rectangle, a window, or the full output (or in the case of screenshot, the full screen).

**Comment by jvanbruegge** [comment] 2020-05-12 07:26
I think would also be interesting to investigate how to offer firefox (and other webrtc clients) a list of screens to share. Usually you can select the screen in the browser itself

**Comment by danshick** [comment] 2020-05-12 14:29
@jvanbruegge I don't think this is possible without a change to the WebRTC codebase. In fact, the whole reason that chromium still hides pipewire behind a build and a feature flag is the "dialog spam" of having to do output selection once in the xdp implementation and a second time in the browser. jgrulich, I believe, has been working on reducing the dialog complexity, but I don't know if those changes landed.

> originally, I had a patch that it didn't show the chromium dialog, it immediately showed the portal dialog and only if you cancelled it, then the Chrome dialog appears with option to share a tab, but Chromium developers didn't like it and they wanted to keep the Chromium dialog as it is

> on Chromium side, I merged "Screen" and "Window" tabs into one, because we don't know what the user will choose and it doesn't make sense to create two capturer classes, then once you pick something in the portal dialog, it will show preview in the Chromium dialog and user just needs to confirm it, then you shouldn't get the portal dialog again, but you should see the screen cast content directly on the web page

 > https://jgrulich.fedorapeople.org/chromium-sharing-screen.webm

**Comment by danshick** [comment] 2020-05-12 14:38
The big difference being that WebRTC itself used to enumerate all screens and windows, and now xdp does it. There's no mechanism in the d-bus api to pass that info to the consumer. The more I think about it, it would not even just be a patch to WebRTC, but to the definition of the xdp screencast portal too.

What I'm thinking for a final selector is a fullscreen overlay similar to slurp, but one which only lets you select entire outputs. I think it should be both keyboard and mouse activated. This can be done with the layer shell protocol, but I haven't gotten around to writing anything just yet.

That said, I'm open to suggestion and PRs.

**Comment by tmccombs** [comment] 2020-05-13 03:53
> a fullscreen overlay similar to slurp, but one which only lets you select entire outputs

so it wouldn't be possible to capture just part of the screen?

**Comment by emersion** [comment] 2020-05-13 07:08
>a fullscreen overlay similar to slurp, but one which only lets you select entire outputs

slurp allows you to provide a set of rectangles on stdin that the user can choose from.

**Comment by danshick** [comment] 2020-05-13 16:01
@emersion  The problem with slurp is that it only outputs coordinates, and for screencasting output selection, we need the output name or ID. Otherwise I would have just done something similar to this and called it a day.

```swaymsg -t get_outputs | jq -r '.[] | select(.active) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp```

I suppose we could get both outputs and their coordinates, invoke slurp, get coordinates back, and map it back to outputs. But, I think it'd be nice to also include a little overlay that explains what's going on, how to select an output, etc... A user invoking slurp has a better grip on the causal relationship of what they're seeing than someone who clicked "share my screen" in the browser. The crosshair cursor and greyed out selection could be a bit confusing without the context.

**Comment by danshick** [comment] 2020-05-13 16:06
@tmccombs 
Screen casting will (likely) never handle anything other than entire outputs. There's no mechanism in wlroots for getting only a single application's buffer.

Screenshots, OTOH, could totally have region selection, as exemplified by slurp + grim. The question is, should invoking a screenshot portal immediately invoke slurp by default? Should a user-selected region be the typical behavior? I'd be curious to see how this works in other portal implementations (gtk, kde). My guess is that the portal should just provide a full screen capture, and the consuming application should do the cropping as needed.

**Comment by tmccombs** [comment] 2020-05-13 18:21
> Screen casting will (likely) never handle anything other than entire outputs.There's no mechanism in wlroots for getting only a single application's buffer.

For single applications buffers, yes. although this is quite unfortunate and a regression from X. However, wlroots does appear to support capturing a region with the "capture_output_region" request in the wlr-screencopy-unstable-v1 protocol. With that it would be possible to use sway ipc to get the region for a particular window, and then capture that region. Although, handling the case of the window moving during a recording would be tricky, since you would need to watch for movement of the window.

> I'd be curious to see how this works in other portal implementations (gtk, kde)

I believe gnome opens a screenshot dialog, although I don't remember exactly what the options are in the dialog.

**Comment by danshick** [comment] 2020-05-13 20:00
Yeah, the window movement issue is the blocker for this for sure. It also isn't possible at all for dmabuf based casting, which we would like to implement eventually.

**Comment by vesim987** [comment] 2020-08-12 15:25
I did a very dirty hack to test that: https://github.com/vesim987/xdg-desktop-portal-wlr/commit/45d5b42dde5f7dee2d29814d08b14449ff0f945c but it is not working too well, especially on chromium. It is executing the setup_outputs function three times, so slurp is executed multiple times too. I don't think that there is a good approach for that w/o fixing the WebRTC spec for allowing output selection.

**Comment by danshick** [comment] 2020-08-12 18:01
There is already some work being done on the "dialog hell" problem as mentioned here[0]. There are a set of patches that seek to improve the situation [1][2] which are currently under review, (and, as a side effect, also improves the situation for #34 by supporting alpha channel pixel formats).

The bigger problem with the idea behind your "dirty hack" is its reliance on swaymsg, which makes this patch sway-specific. We want xdpw to work for all wlroots based compositors. Using the data from the output protocol keeps things agnostic.

[0] https://bugs.chromium.org/p/chromium/issues/detail?id=682122#c58
[1] https://webrtc-review.googlesource.com/c/src/+/160649
[2] https://chromium-review.googlesource.com/c/chromium/src/+/1942327

**Comment by vesim987** [comment] 2020-08-12 19:30
@danshick 
> The bigger problem with the idea behind your "dirty hack" is its reliance on swaymsg, which makes this patch sway-specific. We want xdpw to work for all wlroots based compositors. Using the data from the output protocol keeps things agnostic.

I know, doing that with only slurp is better, there is even a list of the outputs(ctx->output_list) available, but I didn't know about the fixes to WebRTC and I wanted to make something fast to test this. I will try to create some proper patch around the weekend.

**Comment by danshick** [comment] 2020-08-12 20:42
> @danshick 
> > The bigger problem with the idea behind your "dirty hack" is its reliance on swaymsg, which makes this patch sway-specific. We want xdpw to work for all wlroots based compositors. Using the data from the output protocol keeps things agnostic.
> 
> I know, doing that with only slurp is better, there is even a list of the outputs(ctx->output_list) available, but I didn't know about the fixes to WebRTC and I wanted to make something fast to test this. I will try to create some proper patch around the weekend.

Hey, no criticism, you got something working and that's excellent! Just wanted to point out what I'd be thinking about if we were to implement this (I'd also probably try to avoid having jq as a dependency).

Hopefully those webrtc patches are accepted soon.

Thanks for taking interest!

**Comment by tmccombs** [comment] 2020-08-13 07:44
> Screen casting will (likely) never handle anything other than entire outputs. There's no mechanism in wlroots for getting only a single application's buffer.

I'm not sure why this means you can't select a region of an output to capture rather than the entire output.

**Comment by danshick** [comment] 2020-08-13 15:26
> > Screen casting will (likely) never handle anything other than entire outputs. There's no mechanism in wlroots for getting only a single application's buffer.
> 
> I'm not sure why this means you can't select a region of an output to capture rather than the entire output.

You totally can. Finding out the coordinates of that region in a non-Sway specific way is not currently possible. We could use sway-ipc, but then this would no longer work for wayfire/hikari/river/etc.

**Comment by tmccombs** [comment] 2020-08-13 16:33
> Finding out the coordinates of that region in a non-Sway specific way is not currently possible.

Isn't that exactly what slurp does?

**Comment by danshick** [comment] 2020-08-13 20:27
> Isn't that exactly what slurp does?

Not exactly, slurp is just a region selection tool. If you look at slurp's README, you'll see the example they provide for getting a window's region relies on the output of swaymsg.

```
swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp
```

**Comment by tmccombs** [comment] 2020-08-14 00:47
Right, but I'm not talking about selecting a window's region, I mean just draw a rectangle on the screen that you want to capture.

**Comment by danshick** [comment] 2020-08-14 05:34
Sure, that's absolutely possible. How should we enable that? Should the region selection immediately begin any time a window capture is initiated? What happens if the window moves once the capture is initiated? We can't detect that to allow the user to make an update. Same with a workspace change. It doesn't feel like it fits the expectation of window sharing.

I think there's value in implementing this experimentally, but only as a way to prepare for the availability of a protocol that can signal window geometry.

**Comment by vesim987** [comment] 2020-08-15 21:09
@danshick @tmccombs 
So, I created https://github.com/emersion/slurp/compare/master...vesim987:output-selection for slurp, but I have no idea how to get the output name. `xdg_output_unstable_v1.name` for some reasons it not working in latest sway, so I hardcoded the output name to `eDP-1` for testing.

And also I've updated my patch to xdg-desktop-portal-wlr: https://github.com/vesim987/xdg-desktop-portal-wlr/commit/4418f85cd70b9865fe8a53cf32f4c1b1582b0b6d now it depends only on slurp. But there is another issue, the screencasting in chromium is not working, I think that there are some timeouts in the WebRTC part of chromium.

**Comment by tmccombs** [comment] 2020-08-16 07:00
>  but I have no idea how to get the output name. xdg_output_unstable_v1.name for some reasons it not working in latest sway

The name event in the xdg_output protocol is only available in v2. You'll need to support v2 in order to get the name.

**Comment by tmccombs** [comment] 2020-08-16 08:34
I think you would need to change https://github.com/vesim987/slurp/blob/output-selection/main.c#L624 to pass version 2 instead of 1 (or maybe the minimum of 2 and the version of the global object, to be more resilient?).

**Comment by vesim987** [comment] 2020-08-16 09:19
@tmccombs I created PR https://github.com/emersion/slurp/pull/60 in slurp. I think it is a better place to discuss that :)

**Comment by danshick** [comment] 2020-08-19 20:18
Only tangentially related, but I wanted to save these links somewhere. This is phoc's approach to screencopy of a given window blending foreign toplevel and screencopy (they use it for thumbnails).

https://source.puri.sm/Librem5/phoc/-/blob/master/src/phosh.c#L322-506

https://source.puri.sm/Librem5/phoc/-/blob/master/src/render.c#L401-474

**Comment by tmccombs** [comment] 2020-08-20 06:24
I think that is suggested for wlroots her: https://github.com/swaywm/wlr-protocols/issues/93#issuecomment-673355231.

**Comment by danshick** [comment] 2020-09-11 14:59
https://github.com/emersion/slurp/pull/64 has made it possible to implement this capability with slurp.

**Comment by columbarius** [comment] 2020-09-23 11:53
I've implemented an output selector (needs cleanup) using a dmenu style of chooser currently using wofi or bemenu. It currently freezes all running screencasts while selecting the output of the next one.  https://github.com/columbarius/xdg-desktop-portal-wlr/tree/dmenu-chooser

I just added support for slurp, which is currently hardcoded and needs emersion/slurp#64.

**Comment by columbarius** [comment] 2020-10-15 19:08
The patch for a graphical output chooser is ready and needs testing #59. So if you are interested, please build xdpw from https://github.com/columbarius/xdg-desktop-portal-wlr/tree/dmenu-chooser and try it.
Currently there are 3 default chooser supported in this order:
- slurp after https://github.com/emersion/slurp/pull/64
- wofi
- bemenu

If you want to quit a chooser you can press ESC and the next one will launch.
While choosing an output all streams are paused, so please report if that's an issue.
It's structurally setup to support custom chooser's later. 
So please test it and report any errors you encounter to https://github.com/emersion/xdg-desktop-portal-wlr/pull/59.

**Comment by danshick** [comment] 2020-10-27 17:34
> While choosing an output all streams are paused, so please report if that's an issue.

We can split the select sources function right [here](https://github.com/emersion/xdg-desktop-portal-wlr/blob/cb36e0df231b81956bd9cedf8893ec975d14476b/src/screencast/screencast.c#L278) and stash the `msg` in `xdpw_state` and move the reply portion that comes after that line to the setup_outputs function.

Instead of calling setup_outputs directly at this line, we can call an asynchronous chooser function, where the pipes have O_NONBLOCK set on them. Then we can stash the pipes alongside the `msg` pointer watch the pipe FDs in the event loop and call a revised setup_outputs function that accepts an output as an argument, checks for existing instances (like it does currently), and also replies to the d-bus message we stashed earlier.

This should avoid the other streams blocking while we wait for the user to select an output. Definitely don't need to get it done this PR, but I wanted to write this down while I'm thinking about it.

**Comment by Hubro** [comment] 2021-01-28 23:30
@danshick Sorry in advance for a somewhat off topic request, but would you mind opening an issue for "Screencast: Let the user select application window"? I realize this is currently impossible for you to implement because of deficiencies in other libraries/protocols, but it would be great to have an issue I can watch for updates. It's currently the only thing preventing me from using Sway full time, as I have a giant monitor and I have to screencast regularly for work.

**Comment by danshick** [comment] 2021-01-28 23:54
> @danshick Sorry in advance for a somewhat off topic request, but would you mind opening an issue for "Screencast: Let the user select application window"?

I'm out right now but anyone is welcome to create an issue.

**Comment by michelesr** [comment] 2021-01-31 12:51
Looks like GNOME now is showing a dialog which allows you to select the appropriate screen or window:

https://bugzilla.mozilla.org/show_bug.cgi?id=1675764

![screenshot](https://bug1675764.bmoattachments.org/attachment.cgi?id=9186238)

**Comment by tmccombs** [comment] 2021-01-31 17:35
Any idea how that works?

**Comment by michelesr** [comment] 2021-01-31 17:51
@tmccombs not really... I'm not familiar with their codebase, but I guess it was added in https://github.com/flatpak/xdg-desktop-portal-gtk/commit/0d21a347c565feb2d7040c38ac46f9c80840be71 and the main file to look at is https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/screencastdialog.c

**Comment by danshick** [comment] 2021-01-31 18:00
> Any idea how that works?

It's been around for a little while now. IIRC, they use some Gnome-specific protocols to grab window buffers. It isn't something that would be portable to wlroots.

**Comment by tinywrkb** [comment] 2021-01-31 20:27
So what [this is](https://github.com/flathub/org.chromium.Chromium/issues/22#issuecomment-742307156)?  
Specifically [here](https://webrtc.googlesource.com/src/+/40c3ea5c7146cb7ec2fa999143d702b8825b725f): `Window sharing support`  
Is this just Chrome/Chromium windows?

**Comment by danshick** [comment] 2021-02-01 00:49
> So what [this is](https://github.com/flathub/org.chromium.Chromium/issues/22#issuecomment-742307156)?  
> Specifically [here](https://webrtc.googlesource.com/src/+/40c3ea5c7146cb7ec2fa999143d702b8825b725f): `Window sharing support`  
> Is this just Chrome/Chromium windows?

No, this is "window sharing" as you're thinking. Chromium did need some patches because Gnome sends a buffer the size of the full screen with "crop" info to explain where the window is in the image. The image being sent is just that window's buffer painted onto a blank background the size of the screen. This is done so that they can support window moving and resizing by allocating a frame the full size of the screen no matter what (IIRC).

Our challenge isn't support within pipewire or webrtc, but rather the ability to pull a single application's buffers for all surfaces. This is a wlroots limitation.

The toplevel management wayland protocol gets us part of the way there, but I don't remember all of the specifics of what is missing.

**Comment by tmccombs** [comment] 2021-02-01 07:21
Is the problem that there isn't a protocol to get the buffers, in which case a protocol could be created? Or are there deeper problems that would prevent such a feature from being added.  

Of particular interest would be being able to get a screenshot or capture stream of a window that isn't currently visible on screen. That would allow use cases such as:
- Sharing a window, and that window continues to be shown if another app covers it (and if it overlaps with another window, the other window isn't shown)
- Building an expose-like app for sway or other wlroots based compositors (see https://github.com/morrolinux/i3expo-ng) that shows windows  not currently being rendered.

Is there an existing wlroots issue for something like this?

**Comment by emersion** [comment] 2021-02-01 08:28
Issue is here: https://github.com/swaywm/wlr-protocols/issues/93

**Comment by shibumi** [comment] 2021-03-14 13:27
Hey everybody I would like to share my little solution for the problem. I am using xdg-desktop-portal-wlr only for screen sharing (for example in MS Teams). For selecting the correct output I am running this script here right now:

```
input=$(swaymsg -t get_outputs | jq -r '.[].name' | bemenu)
/usr/lib/xdg-desktop-portal -r & /usr/lib/xdg-desktop-portal-wlr -r -o "$input" &
```

The script just catches all connected monitors, shows them via bemenu, let me select one monitor and then it respawns the xdg-desktop-portal-wlr process with the correct output.

This is far from being perfect, I know. I would prefer to have the possibility to choose the correct output directly in the browser, but it solves the problem for me right now.

**Comment by danshick** [comment] 2021-03-15 00:36
@shibumi PR #59 implements a way for xdpw to invoke dmenu style programs or slurp to choose an output for each screensharing request without restarting xdpw.

If you have the inclination and ability to compile @columbarius's branch yourself, helping to test that PR would be welcomed.

**Comment by piater** [comment] 2021-03-15 07:11
FWIW, I have been tracking @columbarius' branch and using it in production for many months, and it has been working well for me, with both Firefox and (ungoogled) Chromium.

**Comment by danshick** [comment] 2021-03-15 15:20
Thanks for the feedback! Good to know it has been stable for you.

**Closed** 2021-04-02 13:07 UTC
Labels: enhancement
