### ISSUE TITLE
Screencast not working with latest chromium (85.0.4183.102)

### ISSUE THREAD

**Issue by joelazar** [emersion/xdg-desktop-portal-wlr#51] opened 2020-09-10 10:16 UTC
I've recently noticed that the screen casting is not working anymore with the current latest chromium (85.0.4183.102) on arch.

```
▶ yay -Q | grep 'sway\|wlr\|pipewire'
bemenu-wlroots 0.4.0-1
libpipewire02 0.2.7-1
pipewire 0.3.10-1
sway 1:1.5-1
swaybg 1.0-4
swayidle 1.6-1
swaylock 1.5-1
wlr-randr 0.1.0-1
wlroots 0.11.0-1
xdg-desktop-portal-wlr 0.1.0-4
```

With the same versions I did manage to get it working with an older chromium version (84.0.4147.135-1) and I gathered the logs from this command (`/usr/lib/xdg-desktop-portal -r & /usr/lib/xdg-desktop-portal-wlr -l DEBUG`) with both of them.

With 85.0.4183.102
```
2020/09/10 12:00:14 [DEBUG] - dbus: connected
2020/09/10 12:00:14 [DEBUG] - wlroots: wl_display connected
2020/09/10 12:00:14 [DEBUG] - pipewire: pw_loop created
2020/09/10 12:00:14 [DEBUG] - pipewire: establishing connection to core
2020/09/10 12:00:14 [DEBUG] - wayland: registry listeners run
2020/09/10 12:00:14 [DEBUG] - wayland: xdg output listeners run
2020/09/10 12:00:28 [INFO] - dbus: create session method invoked
2020/09/10 12:00:28 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_158/webrtc1956488449
2020/09/10 12:00:28 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_158/webrtc_session642066028
2020/09/10 12:00:28 [INFO] - dbus: app_id: 
2020/09/10 12:00:28 [INFO] - dbus: create session method invoked
2020/09/10 12:00:28 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_158/webrtc1814659098
2020/09/10 12:00:28 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_158/webrtc_session169301659
2020/09/10 12:00:28 [INFO] - dbus: app_id: 
2020/09/10 12:00:28 [INFO] - dbus: select sources method invoked
2020/09/10 12:00:28 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_158/webrtc1709508267
2020/09/10 12:00:28 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_158/webrtc_session642066028
2020/09/10 12:00:28 [INFO] - dbus: app_id: 
2020/09/10 12:00:28 [INFO] - dbus: option types:2
2020/09/10 12:00:28 [INFO] - dbus: option multiple: 0
2020/09/10 12:00:28 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_158/webrtc_session642066028
2020/09/10 12:00:28 [INFO] - wlroots: capturable output: Unknown model: 0x05EE: id: 36 name: eDP-1
2020/09/10 12:00:28 [INFO] - xdpw: screencast instance 0x561e5bc482a0 has 1 references
2020/09/10 12:00:28 [INFO] - xdpw: 1 active screencast instances
2020/09/10 12:00:28 [INFO] - wlroots: output: eDP-1
2020/09/10 12:00:28 [INFO] - dbus: select sources method invoked
2020/09/10 12:00:28 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_158/webrtc808493735
2020/09/10 12:00:28 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_158/webrtc_session169301659
2020/09/10 12:00:28 [INFO] - dbus: app_id: 
2020/09/10 12:00:28 [INFO] - dbus: option types:1
2020/09/10 12:00:28 [INFO] - dbus: option multiple: 0
2020/09/10 12:00:28 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_158/webrtc_session169301659
2020/09/10 12:00:28 [INFO] - wlroots: capturable output: Unknown model: 0x05EE: id: 36 name: eDP-1
2020/09/10 12:00:28 [INFO] - xdpw: existing screencast instance: 36 with cursor
2020/09/10 12:00:28 [INFO] - xdpw: screencast instance 0x561e5bc482a0 now has 2 references
2020/09/10 12:00:28 [INFO] - wlroots: output: eDP-1
2020/09/10 12:00:28 [INFO] - dbus: start method invoked
2020/09/10 12:00:28 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_158/webrtc1126261167
2020/09/10 12:00:28 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_158/webrtc_session642066028
2020/09/10 12:00:28 [INFO] - dbus: app_id: 
2020/09/10 12:00:28 [INFO] - dbus: parent_window: 
2020/09/10 12:00:28 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_158/webrtc_session642066028
2020/09/10 12:00:28 [DEBUG] - wlroots: reset buffer
2020/09/10 12:00:28 [DEBUG] - wlroots: create shm buffer
2020/09/10 12:00:28 [DEBUG] - pipewire: registered event 0x561e5bc497e0
2020/09/10 12:00:28 [INFO] - pipewire: stream state changed to "connecting"
2020/09/10 12:00:28 [INFO] - pipewire: node id is -1
2020/09/10 12:00:28 [INFO] - dbus: start method invoked
2020/09/10 12:00:28 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_158/webrtc290854034
2020/09/10 12:00:28 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_158/webrtc_session169301659
2020/09/10 12:00:28 [INFO] - dbus: app_id: 
2020/09/10 12:00:28 [INFO] - dbus: parent_window: 
2020/09/10 12:00:28 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_158/webrtc_session169301659
2020/09/10 12:00:28 [INFO] - pipewire: stream state changed to "paused"
2020/09/10 12:00:28 [INFO] - pipewire: node id is 39
2020/09/10 12:00:28 [INFO] - pipewire: stream state changed to "streaming"
2020/09/10 12:00:28 [INFO] - pipewire: node id is 39
2020/09/10 12:00:53 [INFO] - dbus: session closed
2020/09/10 12:00:53 [DEBUG] - dbus: destroying session 0x561e5bc476d0
2020/09/10 12:00:53 [DEBUG] - xdpw: screencast instance 0x561e5bc482a0 now has 1 references
2020/09/10 12:00:53 [INFO] - pipewire: stream state changed to "paused"
2020/09/10 12:00:53 [INFO] - pipewire: node id is 39
2020/09/10 12:00:53 [INFO] - dbus: session closed
2020/09/10 12:00:53 [DEBUG] - dbus: destroying session 0x561e5bc46160
2020/09/10 12:00:53 [DEBUG] - xdpw: screencast instance 0x561e5bc482a0 now has 0 references
2020/09/10 12:00:53 [INFO] - dbus: create session method invoked
2020/09/10 12:00:53 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_161/webrtc614088471
2020/09/10 12:00:53 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_161/webrtc_session774146506
2020/09/10 12:00:53 [INFO] - dbus: app_id: 
2020/09/10 12:00:53 [DEBUG] - xdpw: destroying cast instance
2020/09/10 12:00:53 [DEBUG] - pipewire: destroying stream
2020/09/10 12:00:53 [INFO] - pipewire: stream state changed to "unconnected"
2020/09/10 12:00:53 [INFO] - pipewire: node id is -1
2020/09/10 12:00:53 [INFO] - dbus: select sources method invoked
2020/09/10 12:00:53 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_161/webrtc1276972935
2020/09/10 12:00:53 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_161/webrtc_session774146506
2020/09/10 12:00:53 [INFO] - dbus: app_id: 
2020/09/10 12:00:53 [INFO] - dbus: option types:1
2020/09/10 12:00:53 [INFO] - dbus: option multiple: 0
2020/09/10 12:00:53 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_161/webrtc_session774146506
2020/09/10 12:00:53 [INFO] - wlroots: capturable output: Unknown model: 0x05EE: id: 36 name: eDP-1
2020/09/10 12:00:53 [INFO] - xdpw: screencast instance 0x561e5bc4abb0 has 1 references
2020/09/10 12:00:53 [INFO] - xdpw: 1 active screencast instances
2020/09/10 12:00:53 [INFO] - wlroots: output: eDP-1
2020/09/10 12:00:53 [INFO] - dbus: start method invoked
2020/09/10 12:00:53 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_161/webrtc245507779
2020/09/10 12:00:53 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_161/webrtc_session774146506
2020/09/10 12:00:53 [INFO] - dbus: app_id: 
2020/09/10 12:00:53 [INFO] - dbus: parent_window: 
2020/09/10 12:00:53 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_161/webrtc_session774146506
2020/09/10 12:00:53 [DEBUG] - wlroots: reset buffer
2020/09/10 12:00:53 [DEBUG] - wlroots: create shm buffer
2020/09/10 12:00:53 [DEBUG] - pipewire: registered event 0x561e5bc4de90
2020/09/10 12:00:53 [INFO] - pipewire: stream state changed to "connecting"
2020/09/10 12:00:53 [INFO] - pipewire: node id is -1
2020/09/10 12:00:53 [INFO] - pipewire: stream state changed to "paused"
2020/09/10 12:00:53 [INFO] - pipewire: node id is 39
```

With 84.0.4147.135-1
```
2020/09/10 12:03:35 [DEBUG] - dbus: connected
2020/09/10 12:03:35 [DEBUG] - wlroots: wl_display connected
2020/09/10 12:03:35 [DEBUG] - pipewire: pw_loop created
2020/09/10 12:03:35 [DEBUG] - pipewire: establishing connection to core
2020/09/10 12:03:35 [DEBUG] - wayland: registry listeners run
2020/09/10 12:03:35 [DEBUG] - wayland: xdg output listeners run
2020/09/10 12:03:45 [INFO] - dbus: create session method invoked
2020/09/10 12:03:45 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc541575562
2020/09/10 12:03:45 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session999036087
2020/09/10 12:03:45 [INFO] - dbus: app_id: 
2020/09/10 12:03:45 [INFO] - dbus: create session method invoked
2020/09/10 12:03:45 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc1323861089
2020/09/10 12:03:45 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session364193999
2020/09/10 12:03:45 [INFO] - dbus: app_id: 
2020/09/10 12:03:45 [INFO] - dbus: select sources method invoked
2020/09/10 12:03:45 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc602564659
2020/09/10 12:03:45 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session999036087
2020/09/10 12:03:45 [INFO] - dbus: app_id: 
2020/09/10 12:03:45 [INFO] - dbus: option types:1
2020/09/10 12:03:45 [INFO] - dbus: option multiple: 0
2020/09/10 12:03:45 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_187/webrtc_session999036087
2020/09/10 12:03:45 [INFO] - wlroots: capturable output: Unknown model: 0x05EE: id: 36 name: eDP-1
2020/09/10 12:03:45 [INFO] - xdpw: screencast instance 0x5599bdb30ff0 has 1 references
2020/09/10 12:03:45 [INFO] - xdpw: 1 active screencast instances
2020/09/10 12:03:45 [INFO] - wlroots: output: eDP-1
2020/09/10 12:03:45 [INFO] - dbus: select sources method invoked
2020/09/10 12:03:45 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc1867875405
2020/09/10 12:03:45 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session364193999
2020/09/10 12:03:45 [INFO] - dbus: app_id: 
2020/09/10 12:03:45 [INFO] - dbus: option types:2
2020/09/10 12:03:45 [INFO] - dbus: option multiple: 0
2020/09/10 12:03:45 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_187/webrtc_session364193999
2020/09/10 12:03:45 [INFO] - wlroots: capturable output: Unknown model: 0x05EE: id: 36 name: eDP-1
2020/09/10 12:03:45 [INFO] - xdpw: existing screencast instance: 36 with cursor
2020/09/10 12:03:45 [INFO] - xdpw: screencast instance 0x5599bdb30ff0 now has 2 references
2020/09/10 12:03:45 [INFO] - wlroots: output: eDP-1
2020/09/10 12:03:45 [INFO] - dbus: start method invoked
2020/09/10 12:03:45 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc520822879
2020/09/10 12:03:45 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session999036087
2020/09/10 12:03:45 [INFO] - dbus: app_id: 
2020/09/10 12:03:45 [INFO] - dbus: parent_window: 
2020/09/10 12:03:45 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_187/webrtc_session999036087
2020/09/10 12:03:45 [DEBUG] - wlroots: reset buffer
2020/09/10 12:03:45 [DEBUG] - wlroots: create shm buffer
2020/09/10 12:03:45 [DEBUG] - pipewire: registered event 0x5599bdb33350
2020/09/10 12:03:45 [INFO] - pipewire: stream state changed to "connecting"
2020/09/10 12:03:45 [INFO] - pipewire: node id is -1
2020/09/10 12:03:45 [INFO] - dbus: start method invoked
2020/09/10 12:03:45 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc1018888514
2020/09/10 12:03:45 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session364193999
2020/09/10 12:03:45 [INFO] - dbus: app_id: 
2020/09/10 12:03:45 [INFO] - dbus: parent_window: 
2020/09/10 12:03:45 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_187/webrtc_session364193999
2020/09/10 12:03:45 [INFO] - pipewire: stream state changed to "paused"
2020/09/10 12:03:45 [INFO] - pipewire: node id is 38
2020/09/10 12:03:45 [INFO] - pipewire: stream state changed to "streaming"
2020/09/10 12:03:45 [INFO] - pipewire: node id is 38
2020/09/10 12:03:48 [INFO] - dbus: session closed
2020/09/10 12:03:48 [DEBUG] - dbus: destroying session 0x5599bdb2fff0
2020/09/10 12:03:48 [DEBUG] - xdpw: screencast instance 0x5599bdb30ff0 now has 1 references
2020/09/10 12:03:48 [INFO] - pipewire: stream state changed to "paused"
2020/09/10 12:03:48 [INFO] - pipewire: node id is 38
2020/09/10 12:03:48 [INFO] - dbus: session closed
2020/09/10 12:03:48 [DEBUG] - dbus: destroying session 0x5599bdb31d70
2020/09/10 12:03:48 [DEBUG] - xdpw: screencast instance 0x5599bdb30ff0 now has 0 references
2020/09/10 12:03:48 [DEBUG] - xdpw: destroying cast instance
2020/09/10 12:03:48 [DEBUG] - pipewire: destroying stream
2020/09/10 12:03:48 [INFO] - pipewire: stream state changed to "unconnected"
2020/09/10 12:03:48 [INFO] - pipewire: node id is -1
2020/09/10 12:03:48 [INFO] - dbus: create session method invoked
2020/09/10 12:03:48 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc1266550025
2020/09/10 12:03:48 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session973914620
2020/09/10 12:03:48 [INFO] - dbus: app_id: 
2020/09/10 12:03:48 [INFO] - dbus: select sources method invoked
2020/09/10 12:03:48 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc955456116
2020/09/10 12:03:48 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session973914620
2020/09/10 12:03:48 [INFO] - dbus: app_id: 
2020/09/10 12:03:48 [INFO] - dbus: option types:1
2020/09/10 12:03:48 [INFO] - dbus: option multiple: 0
2020/09/10 12:03:48 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_187/webrtc_session973914620
2020/09/10 12:03:48 [INFO] - wlroots: capturable output: Unknown model: 0x05EE: id: 36 name: eDP-1
2020/09/10 12:03:48 [INFO] - xdpw: screencast instance 0x5599bdb347c0 has 1 references
2020/09/10 12:03:48 [INFO] - xdpw: 1 active screencast instances
2020/09/10 12:03:48 [INFO] - wlroots: output: eDP-1
2020/09/10 12:03:48 [INFO] - dbus: start method invoked
2020/09/10 12:03:48 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_187/webrtc1025311295
2020/09/10 12:03:48 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_187/webrtc_session973914620
2020/09/10 12:03:48 [INFO] - dbus: app_id: 
2020/09/10 12:03:48 [INFO] - dbus: parent_window: 
2020/09/10 12:03:48 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_187/webrtc_session973914620
2020/09/10 12:03:48 [DEBUG] - wlroots: reset buffer
2020/09/10 12:03:48 [DEBUG] - wlroots: create shm buffer
2020/09/10 12:03:48 [DEBUG] - pipewire: registered event 0x5599bdb31740
2020/09/10 12:03:48 [INFO] - pipewire: stream state changed to "connecting"
2020/09/10 12:03:48 [INFO] - pipewire: node id is -1
2020/09/10 12:03:48 [INFO] - pipewire: stream state changed to "paused"
2020/09/10 12:03:48 [INFO] - pipewire: node id is 38
2020/09/10 12:03:48 [INFO] - pipewire: stream state changed to "streaming"
2020/09/10 12:03:48 [INFO] - pipewire: node id is 38
```

**Comment by joelazar** [comment] 2020-09-10 10:21
What makes it even more funnier that with the new chromium version when the popup window appears for the approval of the screen sharing it looks like it captures the content just fine:
![image](https://user-images.githubusercontent.com/16268238/92717039-e8b77000-f35f-11ea-91b9-8f3ab949847c.png)
but after the approval the sharing breaks:
![image](https://user-images.githubusercontent.com/16268238/92717106-ff5dc700-f35f-11ea-8ef8-c6441a56eac2.png)

**Comment by danshick** [comment] 2020-09-10 17:25
Yup, I'm experiencing the same as of this morning. Looking into it.

**Comment by danshick** [comment] 2020-09-10 20:56
I can't find anything at all that's changed about Chromium between 84 and 85, although I'm no Chromium expert. Every other app I try is working correctly. I also tried some older xdpw commits before we made some changes to buffer reuse and that has no effect.

What's even stranger is that if I continue trying to cast, eventually the preview window breaks (seemingly shows nothing, but actually contains an all white display), but the actual cast starts working.

I'm at a loss for today.

**Comment by pjeanjean** [comment] 2020-09-11 14:03
I'm also running 85.0.4183.102-1 here and I don't have this issue

**Comment by danshick** [comment] 2020-09-11 14:52
@pjeanjean It is normal. Eventually output selection will be enabled by a separate mechanism (see https://github.com/emersion/xdg-desktop-portal-wlr/issues/12)

Can I ask what distro you are using? Both myself and @joelazar are using Arch Linux, so maybe it is a distro specific issue.

**Comment by pjeanjean** [comment] 2020-09-11 15:04
I'm also running Arch, and using sway as WM.

**Comment by danshick** [comment] 2020-09-11 15:18
Can you run this for me so I can compare version numbers (if you use yay, if not, pacman should work).

`yay -Q | grep 'sway\|wlr\|pipewire'`

**Comment by pjeanjean** [comment] 2020-09-11 15:19
```
libpipewire02 0.2.7-1
pipewire 0.3.10-1
sway 1:1.5-1
swaybg 1.0-4
swaylock 1.5-1
wlrobs-hg r47.bcc570977627-1
wlroots 0.11.0-1
xdg-desktop-portal-wlr 0.1.0-4
```

I have another computer running sway on Arch, on which I'm using PipeWire a bit more, I will check if it also works when I get back home and I will report back.

**Comment by danshick** [comment] 2020-09-11 15:23
@pjeanjean Thanks for your help. This is bizarre.

And you're using the regular old chromium package from pacman?

**Comment by pjeanjean** [comment] 2020-09-11 15:23
Yes, I never managed to run chromium-ozone

**Comment by danshick** [comment] 2020-09-11 16:22
Hmmm, very confusing. Thanks for the info. Let me know how things are working on your other system.

**Comment by grizonic** [comment] 2020-09-11 17:40
I've been having the exact same issue for a while now. Downgrading pipewire to pipewire-0.3.2-3.fc32.x86_64 fixed it for me, but it's quite unstable. I think it's making my machine lag a lot (libinput 1.16 complains a lot about lag while/after csting my screen).

I'm on Fedora 32 and Chrome 85.0.4183.102

**Comment by pjeanjean** [comment] 2020-09-11 17:42
Looks like screen sharing also works on my other system.

Funny thing is that I also use Pipewire as audio backend on this one (the first computer I tested was running regular Pulse and JACK2), and it caused segfaults whenever the screencast popup was supposed to open.
I had to run chromium with `apulse` to stop getting segfaults.

**Comment by andreaskem** [comment] 2020-09-21 16:41
I was unable to share my screen in Chromium lately, as well. However, my issue seems to have been fixed in `xdg-desktop-portal` version 1.8.0. I might have hit the bug described [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/270#note_625221). However, for another user, the problem persists.

**Comment by joelazar** [comment] 2020-09-21 16:49
yeah, I just wanted to write the same that it works for me now too with the following setup:
```
▶ yay -Q | grep 'sway\|wlr\|pipewire\|chromium\|xdg'
bemenu-wlroots 0.4.0-1
chromium 85.0.4183.102-1
libpipewire02 0.2.7-1
pipewire 0.3.12-1
sway 1:1.5-1
swaybg 1.0-4
swayidle 1.6-1
swaylock 1.5-1
wlr-randr 0.1.0-2
wlroots 0.11.0-1
xdg-dbus-proxy 0.1.2-2
xdg-desktop-portal 1.8.0-1
xdg-desktop-portal-wlr 0.1.0-4
xdg-utils 1.1.3+19+g9816ebb-1
```

**Comment by danshick** [comment] 2020-09-21 17:01
Glad to hear this is resolved for some in this thread. @grizonic are you also able to resolve your issue by upgrading xdg-desktop-portal?

I'll test this myself shortly and close the issue if it seems fixed.

**Comment by danshick** [comment] 2020-09-21 18:41
Yup, confirmed this is working again.

**Closed by danshick** 2020-09-21 18:41 UTC
Labels: upstream bug
