### ISSUE TITLE
xdg-desktop-portal-wlr not starting

### ISSUE THREAD

**Issue by cristobaltapia** [emersion/xdg-desktop-portal-wlr#68] opened 2020-11-14 00:03 UTC
Hi,
I am running Archlinux with sway and I don't know exactly when this started happening, but xdg-desktop-portal-wlr does not work for me anymore. The following error is shown:

```
❯ systemctl --user status xdg-desktop-portal-wlr.service
● xdg-desktop-portal-wlr.service - Portal service (wlroots implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-wlr.service; static)
     Active: failed (Result: core-dump) since Sat 2020-11-14 00:57:47 CET; 8s ago
    Process: 100998 ExecStart=/usr/lib/xdg-desktop-portal-wlr (code=dumped, signal=SEGV)
   Main PID: 100998 (code=dumped, signal=SEGV)

Nov 14 00:57:47 tapia-laptop systemd-coredump[101001]: Process 100998 (xdg-desktop-por) of user 1000 dumped core.

                                                       Stack trace of thread 100998:
                                                       #0  0x0000559040299741 main (xdg-desktop-portal-wlr + 0x3741)
                                                       #1  0x00007fee9768b152 __libc_start_main (libc.so.6 + 0x28152)
                                                       #2  0x000055904029995e _start (xdg-desktop-portal-wlr + 0x395e)

                                                       Stack trace of thread 100999:
                                                       #0  0x00007fee977635de epoll_wait (libc.so.6 + 0x1005de)
                                                       #1  0x00007fee97a15f51 n/a (libspa-support.so + 0xff51)
                                                       #2  0x00007fee97a0d284 n/a (libspa-support.so + 0x7284)
                                                       #3  0x00007fee9785dff0 n/a (libpipewire-0.3.so.0 + 0x26ff0)
                                                       #4  0x00007fee9763c3e9 start_thread (libpthread.so.0 + 0x93e9)
                                                       #5  0x00007fee97763293 __clone (libc.so.6 + 0x100293)
Nov 14 00:57:47 tapia-laptop systemd[4293]: xdg-desktop-portal-wlr.service: Scheduled restart job, restart counter is at 5.
Nov 14 00:57:47 tapia-laptop systemd[4293]: Stopped Portal service (wlroots implementation).
Nov 14 00:57:47 tapia-laptop systemd[4293]: xdg-desktop-portal-wlr.service: Start request repeated too quickly.
Nov 14 00:57:47 tapia-laptop systemd[4293]: xdg-desktop-portal-wlr.service: Failed with result 'core-dump'.
Nov 14 00:57:47 tapia-laptop systemd[4293]: Failed to start Portal service (wlroots implementation).
```

Maybe related: I am also experiencing [this](https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start) problem with GTK apps taking a while to start. However, the solution stated there does not work for me.

**Comment by danshick** [comment] 2020-11-14 05:13
The logs you posted indicate a core dump, but I don't think you have debugging symbols for xdpw, so that won't help.

I have a theory that xdpw is trying to exit gracefully (for one reason or another) but is segfaulting trying to free memory that was never allocated. I created an issue for that already, but it is secondary to your issue and it just means we don't have any nice log messages.

Can you share the versions of pipewire, xdg-desktop-portal, and xdg-desktop-portal-wlr that you're using? On arch, the output of `pacman -Qi _package-name_` would help. I would definitely recommend upgrading all of them if you haven't.

I think your real issue (including slow to start GTK apps) is improperly set environment variables. I [wrote up an explanation here](https://github.com/emersion/xdg-desktop-portal-wlr/wiki/systemd-user-services,-pam,-and-environment-variables), but long story short, you should probably do what the sway wiki suggested, but for the XDG_CURRENT_DESKTOP variable. This particular writeup is new, and if it is helpful (or not), I'd appreciate feedback.

Let me know how it goes. If you have no luck with tweaking variables or updating packages, we can gather logs from manual runs and possibly get a build with debugging symbols to test.

**Comment by cristobaltapia** [comment] 2020-11-14 11:07
Thank for the explanation. Unfortunately, setting the XDG_CURRENT_DESKTOP variable does not help either (in theory it is already correctly set in `.config/environment.d/envvars.conf`). I added it like this to the sway config file (if that is what you meant):

```
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
exec dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
```

These are the versions of the installed packages:
```
Name            : pipewire
Version         : 0.3.15-2
Description     : Server and user space API to deal with multimedia pipelines
Architecture    : x86_64
URL             : https://pipewire.org
Licenses        : LGPL2.1
Groups          : None
Provides        : libpipewire-0.3.so=0-64
Depends On      : gstreamer  gst-plugins-base  sbc  rtkit  vulkan-icd-loader  bluez-libs  alsa-card-profiles  libdbus-1.so=3-64  libsndfile.so=1-64  libudev.so=1-64  libasound.so=2-64  libsystemd.so=0-64  libglib-2.0.so=0-64  libgobject-2.0.so=0-64
Optional Deps   : pipewire-docs: Documentation
                  pipewire-jack: JACK support
                  pipewire-pulse: PulseAudio support [installed]
Required By     : fedora-firefox-wayland-bin  gnome-remote-desktop  mutter  pipewire-pulse  xdg-desktop-portal  xdg-desktop-portal-wlr-git
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.32 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Tue 10 Nov 2020 07:46:49 PM CET
Install Date    : Thu 12 Nov 2020 08:16:52 AM CET
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature
```

```
Name            : xdg-desktop-portal
Version         : 1.8.0-1
Description     : Desktop integration portals for sandboxed apps
Architecture    : x86_64
URL             : https://github.com/flatpak/xdg-desktop-portal
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : glib2  pipewire  fuse2  geoclue2  xdg-desktop-portal-impl
Optional Deps   : None
Required By     : flatpak  xdg-desktop-portal-wlr-git
Optional For    : snapd
Conflicts With  : None
Replaces        : None
Installed Size  : 1974.67 KiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Sat 19 Sep 2020 01:41:42 AM CEST
Install Date    : Sat 19 Sep 2020 12:18:39 PM CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

```
Name            : xdg-desktop-portal-wlr-git
Version         : v0.1.0.r27.gf0e1de0-1
Description     : xdg-desktop-portal backend for wlroots
Architecture    : x86_64
URL             : https://github.com/emersion/xdg-desktop-portal-wlr
Licenses        : custom:MIT
Groups          : None
Provides        : xdg-desktop-portal-wlr  xdg-desktop-portal-impl
Depends On      : xdg-desktop-portal  pipewire
Optional Deps   : libpipewire02: For Chromium WebRTC desktop screencast (see project GitHub page) [installed]
                  obs-xdg-portal: OBS Studio plugin for XDG Desktop Portal (or wlrobs for direct wlroots integration)
Required By     : xdg-desktop-portal
Optional For    : None
Conflicts With  : xdg-desktop-portal-wlr
Replaces        : None
Installed Size  : 325.53 KiB
Packager        : Unknown Packager
Build Date      : Sat 14 Nov 2020 12:56:26 AM CET
Install Date    : Sat 14 Nov 2020 12:56:51 AM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by danshick** [comment] 2020-11-15 17:48
Okay, let's try starting xdpw manually.

Kill both xdg-desktop-portal and xdg-desktop-portal-wlr and run the following:

```sh
/usr/lib/xdg-desktop-portal -vr & /usr/lib/xdg-desktop-portal-wlr -l DEBUG 2>&1 | tee xdpw.log
```

That log should help shed some light on what's going on.

**Comment by cristobaltapia** [comment] 2020-11-15 18:06
Ok, here is the log:

```
❯ /usr/lib/xdg-desktop-portal -vr & /usr/lib/xdg-desktop-portal-wlr
[1] 5626
XDP: load portals from /usr/share/xdg-desktop-portal/portals
2020/11/15 19:03:36 [ERROR] - pipewire: couldn't connect to context
XDP: loading /usr/share/xdg-desktop-portal/portals/gnome-shell.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.Access
XDP: loading /usr/share/xdg-desktop-portal/portals/gnome-keyring.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.Secret
XDP: loading /usr/share/xdg-desktop-portal/portals/wlr.portal
XDP: portal implementation for sway, Wayfire
XDP: portal implementation supports org.freedesktop.impl.portal.Screenshot
XDP: portal implementation supports org.freedesktop.impl.portal.ScreenCast
XDP: providing portal org.freedesktop.portal.MemoryMonitor
XDP: providing portal org.freedesktop.portal.NetworkMonitor
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: providing portal org.freedesktop.portal.Trash
XDP: providing portal org.freedesktop.portal.GameMode
XDP: providing portal org.freedesktop.portal.Settings
XDP: Using wlr.portal for org.freedesktop.impl.portal.Screenshot in sway
Segmentation fault (core dumped)
```

And after that the following started to appear:

```
** (/usr/lib/xdg-desktop-portal:5626): WARNING **: 19:04:01.412: Failed to create screenshot proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.wlr: Timeout was reached

** (/usr/lib/xdg-desktop-portal:5626): WARNING **: 19:04:01.412: No skeleton to export
XDP: Falling back to gnome-shell.portal for org.freedesktop.impl.portal.Access
XDP: providing portal org.freedesktop.portal.Device
XDP: providing portal org.freedesktop.portal.Location

** (/usr/lib/xdg-desktop-portal:5626): WARNING **: 19:04:01.417: Failed connect to PipeWire: Couldn't connect to PipeWire
XDP: providing portal org.freedesktop.portal.Camera
XDP: Falling back to gnome-keyring.portal for org.freedesktop.impl.portal.Secret
XDP: providing portal org.freedesktop.portal.Secret
XDP: Using wlr.portal for org.freedesktop.impl.portal.ScreenCast in sway

** (/usr/lib/xdg-desktop-portal:5626): WARNING **: 19:04:26.442: Failed to create screen cast proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.wlr: Timeout was reached

** (/usr/lib/xdg-desktop-portal:5626): WARNING **: 19:04:26.442: No skeleton to export
XDP: org.freedesktop.portal.Desktop acquired
```

**Comment by danshick** [comment] 2020-11-15 19:46
```
2020/11/15 19:03:36 [ERROR] - pipewire: couldn't connect to context
```

This is your issue. Are you sure pipewire is running? It should start automatically via socket activation, but for debugging, I would recommend ensuring that it is already running. If you can confirm it is, do its logs contain anything of interest?

It would have been better if you had run the exact command I shared, which would have increased the log level and given us more information. Also, can you confirm that you killed all existing xdp/xdpw instances first.

**Comment by cristobaltapia** [comment] 2020-11-15 20:40
Oh, I wrote it by hand and somehow didn't noticed the entire line. Here it is now:

```
❯ /usr/lib/xdg-desktop-portal -vr & /usr/lib/xdg-desktop-portal-wlr -l DEBUG 2>&1 | tee xdpw.log
2020/11/15 21:30:37 [DEBUG] - dbus: connected
2020/11/15 21:30:37 [DEBUG] - wlroots: wl_display connected
2020/11/15 21:30:37 [DEBUG] - pipewire: pw_loop created
2020/11/15 21:30:37 [DEBUG] - pipewire: establishing connection to core
2020/11/15 21:30:37 [ERROR] - pipewire: couldn't connect to context
```

Pipewire is definitely not starting. The systemd unit is inactive and if I try to start it manually I get this:

```
❯ pipewire
[W][000008194.049377][module-protocol-native.c:386 client_new()] server 0x5557dd0eea40: no peersec: Protocol not available
[W][000008194.049487][module-protocol-native.c:386 client_new()] server 0x5557dd0eea40: no peersec: Protocol not available
[W][000008194.145255][module-protocol-native.c:386 client_new()] server 0x5557dd0eea40: no peersec: Protocol not available
[E][000008194.353121][core.c:71 core_event_error()] core 0x56025b350610: proxy 0x56025b394e40 id:4: bound:-1 seq:4 res:-2 (No such file or directory) msg:"can't create device: No such file or directory"
[E][000008194.353135][media-session.c:1971 core_error()] error id:4 seq:4 res:-2 (No such file or directory): can't create device: No such file or directory
```

I will install the git version and see if that changes anything.

**Comment by danshick** [comment] 2020-11-15 22:23
> Pipewire is definitely not starting. The systemd unit is inactive and if I try to start it manually I get this

You can start pipewire like this for more debugging output. The line mentioned in those pipewire logs is just a generic error handler, so we may need more verbose output.

`PIPEWIRE_DEBUG=3 pipewire`

**Comment by cristobaltapia** [comment] 2020-11-16 20:06
OK. So I run `PIPEWIRE_DEBUG=3 pipewire` and got lots of green output (which I suppose means something good :) ) Then I tried to start the `xdg-desktop-portal-wlr` service and it successfully started. So pipewire is not starting at boot but then it can be started?

**Comment by danshick** [comment] 2020-11-16 20:48
> Then I tried to start the `xdg-desktop-portal-wlr` service and it successfully started. So pipewire is not starting at boot but then it can be started?

I can't say at this point why pipewire is failing to start on boot (or, more likely, as a result of socket activation), but starts fine when run manually. That's a pipewire issue (and one that I can't reproduce, as I have an identical setup with no issues). My recommendation might be to try uninstalling and reinstalling pipewire in case some service/socket files have gotten messed up. Also check on any systemd overrides that might be present for pipewire configs.

It seems like xdpw is working as expected when pipewire is running though, so I am going to close this issue. As you continue to debug pipewire, if you have other questions I can help with, you can @ mention me in this closed issue, or I usually hang around #sway on freenode. If you try to reach me on IRC, nick mention me (danshick) so I get a notification.

**Closed by danshick** 2020-11-16 20:48 UTC
Labels: upstream bug

**Comment by cristobaltapia** [comment] 2020-11-16 21:20
Thanks for your time @danshick ! I solved the problem! (I gues at least). The systemd units for `pipewire.socket` and `pipewire.service` were masked. I unmasked them and now everything is back to normal. I don't know how they got masked... or whether it is ok to unmasked them (?).

**Comment by danshick** [comment] 2020-11-16 22:30
No idea how it would have gotten masked. It definitely shouldn't be. Happy to help and glad it's fixed!

**Comment by noahtallen** [comment] 2021-12-08 21:51
Interestingly, I'm getting the same issue. It fails because it can't connect to pipewire, but the pipewire services are available:

```sh
$ systemctl --user status pipewire.service
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-12-08 13:40:08 PST; 14s ago
TriggeredBy: ● pipewire.socket
   Main PID: 1093 (pipewire)
      Tasks: 2 (limit: 38407)
     Memory: 15.2M
        CPU: 40ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─1093 /usr/bin/pipewire

Dec 08 13:40:08 nt-endeavour systemd[1085]: Started PipeWire Multimedia Service.

~
$ systemctl --user status pipewire.socket
● pipewire.socket - Multimedia System
     Loaded: loaded (/usr/lib/systemd/user/pipewire.socket; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-12-08 13:40:08 PST; 17s ago
   Triggers: ● pipewire.service
     Listen: /run/user/1000/pipewire-0 (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/pipewire.socket

Dec 08 13:40:08 nt-endeavour systemd[1085]: Listening on Multimedia System.

~
$ systemctl --user status xdg-desktop-portal-wlr
× xdg-desktop-portal-wlr.service - Portal service (wlroots implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-wlr.service; static)
     Active: failed (Result: exit-code) since Wed 2021-12-08 13:40:36 PST; 1s ago
    Process: 1806 ExecStart=/usr/lib/xdg-desktop-portal-wlr (code=exited, status=1/FAILURE)
   Main PID: 1806 (code=exited, status=1/FAILURE)
        CPU: 5ms

Dec 08 13:40:36 nt-endeavour systemd[1085]: xdg-desktop-portal-wlr.service: Scheduled restart job, restart counter is at 5.
Dec 08 13:40:36 nt-endeavour systemd[1085]: Stopped Portal service (wlroots implementation).
Dec 08 13:40:36 nt-endeavour systemd[1085]: xdg-desktop-portal-wlr.service: Start request repeated too quickly.
Dec 08 13:40:36 nt-endeavour systemd[1085]: xdg-desktop-portal-wlr.service: Failed with result 'exit-code'.
Dec 08 13:40:36 nt-endeavour systemd[1085]: Failed to start Portal service (wlroots implementation).

~
$ /usr/lib/xdg-desktop-portal -vr & /usr/lib/xdg-desktop-portal-wlr -l DEBUG 2>&1 | tee xdpw.log
[1] 1846
2021/12/08 13:40:43 [ERROR] - config: no config file found
2021/12/08 13:40:43 [DEBUG] - config: outputname:  (null)
2021/12/08 13:40:43 [DEBUG] - config: max_fps:  0.000000
2021/12/08 13:40:43 [DEBUG] - config: exec_before:  (null)
2021/12/08 13:40:43 [DEBUG] - config: exec_after:  (null)
2021/12/08 13:40:43 [DEBUG] - config: chooser_cmd: (null)
2021/12/08 13:40:43 [DEBUG] - config: chooser_type: default
XDP: load portals from /usr/share/xdg-desktop-portal/portals
2021/12/08 13:40:43 [DEBUG] - dbus: connected
2021/12/08 13:40:43 [DEBUG] - wlroots: wl_display connected
2021/12/08 13:40:43 [DEBUG] - pipewire: pw_loop created
2021/12/08 13:40:43 [DEBUG] - pipewire: establishing connection to core
XDP: loading /usr/share/xdg-desktop-portal/portals/wlr.portal
XDP: portal implementation for wlroots, sway, Wayfire, river
XDP: portal implementation supports org.freedesktop.impl.portal.Screenshot
XDP: portal implementation supports org.freedesktop.impl.portal.ScreenCast
XDP: loading /usr/share/xdg-desktop-portal/portals/gtk.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.FileChooser
XDP: portal implementation supports org.freedesktop.impl.portal.AppChooser
XDP: portal implementation supports org.freedesktop.impl.portal.Print
XDP: portal implementation supports org.freedesktop.impl.portal.Notification
XDP: portal implementation supports org.freedesktop.impl.portal.Inhibit
XDP: portal implementation supports org.freedesktop.impl.portal.Access
XDP: portal implementation supports org.freedesktop.impl.portal.Account
XDP: portal implementation supports org.freedesktop.impl.portal.Email
XDP: portal implementation supports org.freedesktop.impl.portal.Lockdown
XDP: portal implementation supports org.freedesktop.impl.portal.Settings
XDP: loading /usr/share/xdg-desktop-portal/portals/gnome-keyring.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.Secret
2021/12/08 13:40:43 [ERROR] - pipewire: couldn't connect to context
2021/12/08 13:40:43 [DEBUG] - pipewire: disconnecting fom core
2021/12/08 13:40:43 [ERROR] - xdpw: failed to initialize screencast
```
