### ISSUE TITLE
bad font rendering in Firefox (flatpak) after switching to xdg-desktop-portal-wlr 0.1.0-5

### ISSUE THREAD

**Issue by jokeyrhyme** [emersion/xdg-desktop-portal-wlr#80] opened 2021-01-28 05:32 UTC
Howdie, thanks so much for sharing this project!

I'm not sure if this is the best place to report this, but I figured I'd get it out in writing so at least others can follow the trail

I'm using the Firefox 85 flatpak on Archlinux, and I'm switching between xdg-desktop-portal-wlr 0.1.0-5 and xdg-desktop-portal-gtk 1.8.0-1

I've noticed that with ...-wlr, font rendering is blocky and unpleasant, almost as though scaling is wrong or something

But this goes away when I switch back to ...-gtk

When I'm using ...-wlr, I can see with systemctl that the service is loaded successfully

Weirdly, the Slack and Discord flatpak apps are unaffected, they render fonts just as expected no matter what

So, it's entirely possible this is a Firefox issue, but it's just weird that it coincides with switching portal implementations

**Comment by sentriz** [comment] 2021-01-28 08:38
Does your issue sound like this?
https://github.com/flatpak/flatpak/issues/2861

If so, you may need to install gnome-settings-daemon for the meantime

On 28 January 2021 05:32:46 GMT, Ron Waldon <notifications@github.com> wrote:
>Howdie, thanks so much for sharing this project!
>
>I'm not sure if this is the best place to report this, but I figured I'd get it out in writing so at least others can follow the trail
>
>I'm using the Firefox flatpak on Archlinux, and I'm switching between xdg-desktop-portal-wlr 0.1.0-5 and xdg-desktop-portal-gtk 1.8.0-1
>
>I've noticed that with ...-wlr, font rendering is blocky and unpleasant, almost as though scaling is wrong or something
>
>But this goes away when I switch back to ...-gtk
>
>When I'm using ...-wlr, I can see with systemctl that the service is loaded successfully
>
>Weirdly, the Slack and Discord flatpak apps are unaffected, they render fonts just as expected no matter what
>
>So, it's entirely possible this is a Firefox issue, but it's just weird that it coincides with switching portal implementations
>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jokeyrhyme** [comment] 2021-01-28 09:40
I do have gnome-settings-daemon and gsettings-desktop-schemas installed, and it seems they are necessary to get xdg-desktop-portal-gtk working as expected

Interesting, reading through that issue you linked, from this comment onwards: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/issues/31

> You definitely need xdg-desktop-portal-gtk because that's what provides the gsettings-based settings portal. If you are getting antialiasing without that, it probably means you're using a legacy/insecure flatpak that has access to host dconf, which is not recommended.

> I really mean xdg-desktop-portal-gtk. As I said above, that's what contains the settings portal. There is no way for flatpak apps (or WebKit) to see host GTK settings without it.

From flatpak's API documentation: https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Settings

>  This interface provides read-only access to a small number of host settings required for toolkits similar to XSettings. It is not for general purpose settings.
> Currently the valid keys are entirely implementation details that are undocumented. If you are a toolkit and want to use this please open an issue. 

I wonder if it would help if xdg-desktop-portal-wlr implemented the font configuration parts of the settings portal similar to the way ...-gtk does? https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/settings.c 

Anyhow, this is probably beyond the scope of this project :shrug: 

There is a comment here that is interesting: https://github.com/flatpak/flatpak/issues/2861#issuecomment-743750577

> Ultimately though, I do think this portal needs to be split in two: the gnome portal, and the gtk portal. The GTK would be a hard dependency, since it's required for any GTK application, as discussed above. Meanwhile the gnome-portal one would only run if XDG_CURRENT_DESKTOP contains gnome, and have all the gnome-specific behaviour. Sadly, I don't see this happening, since GTK and GNOME are moving into become one single thing, rather than two separate components.

So, either ...-gtk splits as suggested here so there's a GNOME-specific portal, or perhaps ...-wlr could maybe perform some of the GTK-but-not-GNOME functionality of ...-gtk ?

**Comment by sentriz** [comment] 2021-01-28 09:44
I the idea of xdpw implementing the Settings interface has been raised before here: https://github.com/emersion/xdg-desktop-portal-wlr/issues/40

**Comment by danshick** [comment] 2021-01-28 16:16
You can have both portals installed simultaneously. Requests to portal interfaces that we don't implement (anything other than Screenshot and ScreenCast at the moment) will fall back to other installed implementations.

If you are an active flatpak user, I would strongly encourage keeping the gtk portal installed. It will be necessary for many flatpak functions to work properly.

If you switch compositors often or want to prefer different implementations (when there is more than one installed to choose from), look into setting the XDG_CURRENT_DESKTOP variable. It must be done in a place where xdg-desktop-portal can see it. As this is often started as a user service, it isn't sufficient to put it in your .profile or .bashrc file most of the time. We recommend including it in a wrapper script that starts your compositor, but a more detailed writeup exists on the Wiki.

I'm closing this issue as invalid/wontfix, but I'm happy to continue using the comment space below to help you troubleshoot if these suggestions don't work for you.

**Closed** 2021-01-28 16:17 UTC
Labels: invalid, wontfix

**Comment by jokeyrhyme** [comment] 2021-01-28 19:27
Awesome, thanks

I've installed both:

```
❯ paru -Qs xdg-desktop-portal
local/xdg-desktop-portal 1.8.0-1
    Desktop integration portals for sandboxed apps
local/xdg-desktop-portal-gtk 1.8.0-1
    A GTK+ backend for xdg-desktop-portal
local/xdg-desktop-portal-wlr 0.1.0-5
    xdg-desktop-portal backend for wlroots
```

And the script that launches `sway` sets these first:

```
❯ env | grep DESKTOP
XDG_CURRENT_DESKTOP=sway:GNOME
XDG_SESSION_DESKTOP=sway
```

But, only the GTK portal has launched, is that expected?

```
❯ systemctl --user status xdg-desktop-portal-gtk.service
● xdg-desktop-portal-gtk.service - Portal service (GTK+/GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gtk.service; static)
     Active: active (running) since Fri 2021-01-29 06:23:16 AEDT; 1min 7s ago
   Main PID: 1457 (xdg-desktop-por)
     CGroup: /user.slice/user-60222.slice/user@60222.service/app.slice/xdg-desktop-portal-gtk.service
             └─1457 /usr/lib/xdg-desktop-portal-gtk

Jan 29 06:23:16 hellmouth systemd[1294]: Starting Portal service (GTK+/GNOME implementation)...
Jan 29 06:23:16 hellmouth systemd[1294]: Started Portal service (GTK+/GNOME implementation).

❯ systemctl --user status xdg-desktop-portal-wlr.service
● xdg-desktop-portal-wlr.service - Portal service (wlroots implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-wlr.service; static)
     Active: inactive (dead)
```

**Comment by danshick** [comment] 2021-01-29 01:22
> And the script that launches `sway` sets these first:
> 
> ```
> ❯ env | grep DESKTOP
> XDG_CURRENT_DESKTOP=sway:GNOME
> XDG_SESSION_DESKTOP=sway
> ```

Two things, don't set `XDG_CURRENT_DESKTOP=sway:GNOME`. For one, I think that colon should be a semicolon, and if the whole string `sway:GNOME` doesn't match any implementation, xdp-gtk will likely get chosen as the one and only fallback.

Secondly, both don't even need to be present in the variable. Just set it to `XDG_CURRENT_DESKTOP=sway`. The fallback will still work. This variable just sets preference, it doesn't prevent other implementations from starting to satisfy unimplemented interfaces. The xdp logic may still choose Gnome's screencast implementation first over wlr's if both are present in the variable (I haven't checked what influence order has on this variable). As the Gnome portal implements all interfaces, it will never need to start the wlr implementation if it starts first.

**Comment by jokeyrhyme** [comment] 2021-01-29 03:16
Looks like it splits on colon: https://github.com/flatpak/xdg-desktop-portal/blob/9a2582d035a397efbb330c53f893d5649c1fd749/src/portal-impl.c#L189

I'll test just with `=sway` and report back

**Comment by jokeyrhyme** [comment] 2021-01-29 04:11
Okay, I've rebooted with `XDG_CURRENT_DESKTOP=sway`, and I'm still seeing the systemd unit for xdp-gtk activating whilst xdg-wlr stays inactive

I was hoping -wlr would be active and -gtk would be the fallback, but this might be normal for my setup

"portal" stuff in my logs:

```
❯ journalctl -xb | grep portal
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Activating via systemd: service name='org.freedesktop.portal.Desktop' unit='xdg-desktop-portal.service' requested by ':1.7' (uid=60222 pid=1375 comm="waybar -b bar-0 ")
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Activating via systemd: service name='org.freedesktop.portal.Documents' unit='xdg-document-portal.service' requested by ':1.18' (uid=60222 pid=1439 comm="/usr/lib/xdg-desktop-portal ")
Jan 29 15:04:54 hellmouth systemd[1299]: Starting flatpak document portal service...
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Activating via systemd: service name='org.freedesktop.impl.portal.PermissionStore' unit='xdg-permission-store.service' requested by ':1.19' (uid=60222 pid=1443 comm="/usr/lib/xdg-document-portal ")
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Successfully activated service 'org.freedesktop.portal.Documents'
Jan 29 15:04:54 hellmouth systemd[1299]: Started flatpak document portal service.
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Activating via systemd: service name='org.freedesktop.impl.portal.desktop.gtk' unit='xdg-desktop-portal-gtk.service' requested by ':1.18' (uid=60222 pid=1439 comm="/usr/lib/xdg-desktop-portal ")
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Activating service name='ca.desrt.dconf' requested by ':1.23' (uid=60222 pid=1458 comm="/usr/lib/xdg-desktop-portal-gtk ")
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Successfully activated service 'org.freedesktop.impl.portal.desktop.gtk'
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Activating service name='org.freedesktop.secrets' requested by ':1.18' (uid=60222 pid=1439 comm="/usr/lib/xdg-desktop-portal ")
Jan 29 15:04:54 hellmouth dbus-daemon[1316]: [session uid=60222 pid=1316] Successfully activated service 'org.freedesktop.portal.Desktop'
Jan 29 15:05:23 hellmouth xdg-desktop-por[1439]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list
```

I assume -wlr would be activated if an application requested a portal that was not implemented by -gtk

**Comment by danshick** [comment] 2021-01-29 13:42
> Looks like it splits on colon: https://github.com/flatpak/xdg-desktop-portal/blob/9a2582d035a397efbb330c53f893d5649c1fd749/src/portal-impl.c#L189
> 
> I'll test just with `=sway` and report back

Huh, you're right. Good catch. Either way, only sway is better.

**Comment by danshick** [comment] 2021-01-29 13:50
> I assume -wlr would be activated if an application requested a portal that was not implemented by -gtk

The problem is that -gtk implements all portals, just that the screenshot and cast portals won't work on a wlroots compositor. The implementation choice is made at invocation, even if it fails.

There's one of two reasons this is still failing. The `wlr.portal` file from this repo isn't installed properly or the environment variable isn't set by the time that xdp is started for your session.

The former is verifiable by checking that wlr.portal made it into the correct directory on your system. You could test the latter by running both xdp and xdpw manually from a terminal where the variable is confirmed set.

**Comment by jokeyrhyme** [comment] 2021-02-27 08:11
Oh, just for future reference, I realised that I was setting XDG_CURRENT_DESKTOP in my shell environment from which I spawn `sway`, which isn't sufficient to for that environment variable to be used for my xdg-desktop-portal process

So, I use `systemctl import-environment XDG_CURRENT_DESKTOP`, and now xdg-desktop-portal is correctly spawning both -gtk and -wlr

**Comment by danshick** [comment] 2021-02-27 14:01
@jokeyrhyme

That's discussed at length in the wiki. Maybe we can make that more obvious to new users with better linking or documentation.

https://github.com/emersion/xdg-desktop-portal-wlr/wiki/systemd-user-services,-pam,-and-environment-variables
