### ISSUE TITLE
Screensharing doesn't seem to work with Chromium

### ISSUE THREAD

**Issue by nostdm** [emersion/xdg-desktop-portal-wlr#21] opened 2020-04-03 05:43 UTC
**System:** Arch Linux (sway)

I managed to get the `xdg-desktop-portal-wlr` to work with `fedora-firefox-wayland-bin` as per instructions but I couldn't get it to work with Chromium.

I tried `chromium` package from standard Arch repositories - it resulted in a black screen with a mouse cursor.

I tried enabling pipewire in the chrome://flags configuration options, this resulted in a completely blank screen (no cursor).

I then installed the `chromium-ozone` package from AUR with wayland support and this resulted in a segfault which I think is the same thing mentioned here https://github.com/emersion/xdg-desktop-portal-wlr/issues/20

Relevant packages installed on my system:

```
~ # pacman -Qs pipewire
local/libpipewire02 0.2.7-1
    User space API to deal with multimedia pipelines (0.2)
local/pipewire 0.3.2-1
    Server and user space API to deal with multimedia pipelines
```

```
~ # pacman -Qs chromium
local/chromium-dev-ozone 81.0.4044.17-1
    Chromium built with patches for wayland support via Ozone (dev channel)
```
```
~ # pacman -Qs xdg-desktop-portal
local/xdg-desktop-portal 1.6.0-2
    Desktop integration portals for sandboxed apps
local/xdg-desktop-portal-wlr r24.ccc8a31-1
    xdg-desktop-portal backend for wlroots
```

**Comment by danshick** [comment] 2020-04-03 14:31
Yes, this is a duplicate issue of #20, which is itself a duplicate of #13, but at least shows a novel failure case. I'll leave #20 open, but I'm closing this one.

**Closed by danshick** 2020-04-03 14:31 UTC
