### ISSUE TITLE
Possibility of crowd-funding to move things along

### ISSUE THREAD

**Issue by Tormen** [emersion/xdg-desktop-portal-wlr#8] opened 2019-10-10 18:38 UTC
Dear @emersion ,

first I wanted to thank you for all your efforts in driving so many sway related bits and pieces!!!
I love sway and would not want to miss it.

Only one big pain point remains: Lack of screen sharing support (e.g. via zoom linux app, which works fine under GNOME).

Hence my interest in this project. 

Do you see any chance we or I could organise crowd-funding (I am willing to pay 200 EUR for this) in order to speed things up / drive that project forward into a usable state?

Thanks a lot in advance for your feedback!

Tormen

**Comment by ddevault** [comment] 2019-10-11 17:15
I think the issue is more related to lack of interest than lack of money. If you are interested in this project, perhaps you could step up and write some patches?

**Comment by siwyd** [comment] 2019-10-11 18:02
Lots of interest, zero C skills ;)

**Comment by ddevault** [comment] 2019-10-11 18:02
C is not especially difficult to learn.

**Comment by siwyd** [comment] 2019-10-11 18:31
Time is hard to come by right now unfortunately *sigh*.

**Comment by emersion** [comment] 2019-10-11 18:37
Thanks for your interest in the project!

Right now the main issue is that I have a finite amount of time and focus on other projects. I still want to work on this at some point, but I can't guarantee when.

**Comment by ThenAndNow** [comment] 2019-10-30 18:22
I recommend using Gitcoin to help fund open source work, as a result of this post I actually set up a $50 bounty on the screencast issue https://github.com/emersion/xdg-desktop-portal-wlr/issues/1

**Comment by ddevault** [comment] 2019-10-30 18:30
>which part is proprietary

Where is the source code for gitcoin.io or any of the tools on it?

>Why is this anything but a good thing? Developer gets paid, I'm happy because an issue I care about gets fixed that's a definition of win-win.

Because it removes the maintainers from the loop. Handling money in an open source project is a delicate issue that requires the maintainer's full support. Just arbitrarily assuming your crap is welcome in every open source project is an awful idea, it's been done before and it was terrible then too.

**Comment by ddevault** [comment] 2019-10-30 18:32
And furthermore: how much money does Gitcoin scrape off of the top? It's a business, they're not altruistic, they're a leech on open source software.

**Comment by ThenAndNow** [comment] 2019-10-30 18:34
> Where is the source code for gitcoin.io or any of the tools on it?
The whole thing happens on the blockchain so it's transparent, unless you're talking about the source code for the Gitcoin website but I don't understand why you'd want that.

> Because it removes the maintainers from the loop. Handling money in an open source project is a delicate issue that requires the maintainer's full support. Just arbitrarily assuming your crap is welcome in every open source project is an awful idea, it's been done before and it was terrible then too.
Well, why can't the maintainer claim the reward? And also if someone else is motivated by the reward and submits good code, should it not matter why they did it, but that the code works?

> And furthermore: how much money does Gitcoin scrape off of the top? It's a business, they're not altruistic, they're a leech on open source software.
10% which I already paid up front i.e. $55 out of which $50 went to the issue.

**Comment by ThenAndNow** [comment] 2019-10-30 18:38
BountySource is another popular service with similar objectives, and they also take 10% but at payout. If there was a better alternative I would do that, or are you upset that I didn't donate to your patron account instead?

**Comment by ddevault** [comment] 2019-10-30 18:40
BountySource is another godawful shit pile, I had to ask them no less than *five* times to take my projects off of their platform. And it's no skin off my back if you aren't donating to my patreon account, this isn't even my GitHub repository.

Out of curiosity, are you failing to disclose any vested interest in gitcoin? You have no activity on your GitHub account whatsoever. Suspicious.

**Comment by ThenAndNow** [comment] 2019-10-30 18:42
Yes I work for CIA and FBI and I found this obscure issue with 5 comments and decided it was a brilliant idea to market Gitcoin right here where 3 people will see it. Genius!

**Comment by ThenAndNow** [comment] 2019-10-30 18:58
@ddevault I hope you're not the one upvoting all of your own posts.

**Comment by ddevault** [comment] 2019-10-30 18:58
lol, hover over it and see for youself who did it.

**Comment by ThenAndNow** [comment] 2019-10-30 18:59
It doesn't say

**Comment by ddevault** [comment] 2019-10-30 19:00
![](https://sr.ht/6h1b.png)

**Comment by ThenAndNow** [comment] 2019-10-30 19:00
Is that your other account?

**Comment by freed00m** [comment] 2019-10-30 19:01
@ThenAndNow no I am a real person. You know there are more people involved in open source.

**Comment by ThenAndNow** [comment] 2019-10-30 19:02
Well I honestly didn't expect that donating my own money to help with development would be met with such hostility

**Comment by ddevault** [comment] 2019-10-30 19:03
I'm not hostile towards you, but the friends you keep.

**Comment by ThenAndNow** [comment] 2019-10-30 19:04
Can you stop with this conspiracy bullshit, I created a new account because it's my first time using Gitcoin so I didn't want to share my personal information with them in order to log in.

**Comment by ddevault** [comment] 2019-10-30 19:05
Even if you're not affliated with Gitcoin, you've thrown your lot in with them. That's what I'm referring to here.

**Comment by ThenAndNow** [comment] 2019-10-30 19:08
You totally made me not want to contribute to sway now, which I planned to do next year, but since I work full time I thought I might as well donate some money to move things along. Sad really.

**Comment by ddevault** [comment] 2019-10-30 19:10
I'm playing a ballad for your missing sway contribution on the world's tiniest violin. One patch is not worth submitting to yet another proprietary rent seeking leech of a business.

**Comment by Jamedjo** [comment] 2019-10-30 19:33
Please keep the discussion civil, there are good intentions and reasons all around here :cry:

I was interested enough to put a couple of weekends into this, but didn't get very far. I'll try and come back and help out more, but it does look like progress has been made since then. For zoom specifically we might need to imitate Gnome's screenshot DBUS because it didin't attempt to use the screensharing one back when I last checked. Funnily I spend most my time getting paid to work on the uninteresting things people need 😛

**Comment by owocki** [comment] 2019-10-30 19:33
hi from gitcoin.. sorry about this; 

1. @ddevault  to answer a question above.. we are open source and available at https://github.com/gitcoinco/web - if you dont like anything were doing ur welcome to fork it (GPLv3) and change it.. 
2. we try to encourage bounty funders to check with repo maintainers before posting a bounty but sometimes that lessson is learnt the hard way (nervous laughter...)  i think that your repo should be soveirgn to your value set and we want to respect that (even if not everything to configure that deeply exists yet)
3.i will make sure that @ddevault 's repos are blacklisted from gitcoin.. this is what i said to him on email:

```
back to the blacklist -- It's not built right  now, but I'm going to add a TODO list item to hack something together .. It might take a day or two.. Thanks in advance for your understanding.
```

**Comment by ddevault** [comment] 2019-10-30 19:34
Where do you encourage bounty funders to talk to the maintainers? You could eliminate the problem entirely by letting maintainers *choose* to participate first.

**Comment by ThenAndNow** [comment] 2019-10-30 19:42
Or you could just not use a public website like GitHub and set up your own Git hosting site where no one will bother you.

**Comment by ThenAndNow** [comment] 2019-10-30 19:44
Part of opening your project to the open source world is the fact that all kinds of people will come with all kinds of ideas, part of being a successful open source maintainer is the ability to handle people gracefully.

**Comment by ddevault** [comment] 2019-10-30 19:45
You say that like every idea has value. In reality, some ideas even have negative value, like this one.

**Comment by ddevault** [comment] 2019-10-30 19:46
And I think I'm demonstratbly a pretty successful open source maintainer, too :smile:

**Comment by ThenAndNow** [comment] 2019-10-30 19:48
I wish your projects ware as polished as your ego.

**Comment by foxcpp** [comment] 2019-10-30 21:20
Can we close & lock this issue to stop that pointless flamewar? Looks like the initial question was already answered in the first two replies from @emersion. By looking at gitcoinbot replies marked as spam (by emersion) I can assume he is not interested in its use, so don't bring it up again.

**Closed** 2019-10-30 21:22 UTC
